/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "background": "#131313",
        "outline": "#a28d7d",
        "on-tertiary-fixed": "#410006",
        "on-background": "#e5e2e1",
        "on-primary-container": "#6d3a00",
        "error": "#ffb4ab",
        "on-primary": "#4c2700",
        "on-primary-fixed-variant": "#6d3a00",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed-variant": "#8c1520",
        "surface-container": "#201f1f",
        "tertiary-fixed": "#ffdad8",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#ffb77a",
        "tertiary-fixed-dim": "#ffb3b0",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdcc2",
        "on-secondary-container": "#00302c",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed-dim": "#71d7cd",
        "on-secondary": "#003733",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed": "#2e1500",
        "on-tertiary": "#68000f",
        "tertiary-container": "#ff9a97",
        "primary": "#ffc697",
        "secondary-fixed": "#8ef4e9",
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#dac2b1",
        "primary-container": "#ff9f43",
        "outline-variant": "#544437",
        "tertiary": "#ffc3c0",
        "surface-variant": "#353534",
        "on-secondary-fixed-variant": "#00504a",
        "on-tertiary-container": "#8d1620",
        "on-secondary-fixed": "#00201d",
        "surface-bright": "#393939",
        "surface": "#131313",
        "secondary-container": "#32a097",
        "secondary": "#71d7cd",
        "inverse-primary": "#8f4e00",
        "on-error": "#690005",
        "surface-tint": "#ffb77a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "32px",
        "container-margin": "20px",
        "md": "16px",
        "gutter": "16px",
        "base": "8px",
        "lg": "24px",
        "xs": "4px",
        "sm": "12px"
      },
      "fontFamily": {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
